/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package MovieAndMusicStoreUI;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

/**
 *
 * @author Sameer
 */
public class Populate_Tables extends javax.swing.JFrame {

    
    static Connection conn = null;
    /**
     * Creates new form Populate_Tables
     */
    public Populate_Tables() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("INSERT INTO");

        jButton1.setText("EMPLOYEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("STORE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("MANUFACTURER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("PRODUCT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String[] arr = {"INSERT INTO EMPLOYEE VALUES ('Bob', 10, 15)",
            "INSERT INTO EMPLOYEE VALUES ('Alice', 6, 15)",
            "INSERT INTO EMPLOYEE VALUES ('Calvin', 15, 22)",
            "INSERT INTO EMPLOYEE VALUES ('Carl', 21, 22)",
            "INSERT INTO EMPLOYEE VALUES ('Jordan', 22, 80)",
            "INSERT INTO EMPLOYEE VALUES ('Sameer', 55, 15)",
            "INSERT INTO EMPLOYEE VALUES ('Renzo', 67, 80)",
            "INSERT INTO EMPLOYEE VALUES ('Michael', 14, 22)",
            "INSERT INTO EMPLOYEE VALUES ('Jack', 80, 70)"
        };
        
        Database.ConnectToDB();
        String[] attr = new String[20];
        String temp = "";
     
        for(int a = 0; a < arr.length; a++ )
        {
            try{
                        Statement st = conn.createStatement();
                        ResultSet rs = st.executeQuery(arr[a]);
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int cn = rsmd.getColumnCount();
                        

                        while (rs.next()) {
                            for(int i = 0; i<cn; i++){
                                    attr[i] = rs.getString(i+1).toString();
                            }
                            for(int i = 0; i<cn; i++){
                                    //System.out.print(attr[i] + "\t\t");
                                    temp = temp + attr[i] + "\t\t";
                            }
                            //System.out.println("");
                            temp = temp + "\n";
                        }
                        jTextArea1.setText(temp);
                        rs.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
       
        
        String[] arr = {"INSERT INTO STORE VALUES ('HMV', '59 Main St', 15, 200)",
            "INSERT INTO STORE VALUES ('MM Shop', '61 Oak St', 70, 340)",
            "INSERT INTO STORE VALUES ('DVD Stop', '99 Pine St', 22, 131)",
            "INSERT INTO STORE VALUES ('Bludef', '23 Spruce St', 80, 556)",
            "INSERT INTO STORE VALUES ('Redshift Records', '77 Rye St', 39, 678)",
            "INSERT INTO STORE VALUES ('Videocom', '83 Front St', 15, 193)"
        };
        
        Database.ConnectToDB();
        String[] attr = new String[20];
        String temp = "";
     
        for(int a = 0; a < arr.length; a++ )
        {
            try{
                        Statement st = conn.createStatement();
                        ResultSet rs = st.executeQuery(arr[a]);
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int cn = rsmd.getColumnCount();
                        

                        while (rs.next()) {
                            for(int i = 0; i<cn; i++){
                                    attr[i] = rs.getString(i+1).toString();
                            }
                            for(int i = 0; i<cn; i++){
                                    //System.out.print(attr[i] + "\t\t");
                                    temp = temp + attr[i] + "\t\t";
                            }
                            //System.out.println("");
                            temp = temp + "\n";
                        }
                        jTextArea1.setText(temp);
                        rs.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } 
        } 
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
        String[] arr = {"INSERT INTO MANUFACTURER VALUES ('Music Makers', '12 Main St', 2156)",
            "INSERT INTO MANUFACTURER VALUES ('CDs R Us', '10 Moon Ave', 3001)",
            "INSERT INTO MANUFACTURER VALUES ('Compacters', '200 Sun St', 2090)",
            "INSERT INTO MANUFACTURER VALUES ('Filmworks', '54 Bay St', 1001)"
        };
        
        Database.ConnectToDB();
        String[] attr = new String[20];
        String temp = "";
     
        for(int a = 0; a < arr.length; a++ )
        {
            try{
                        Statement st = conn.createStatement();
                        ResultSet rs = st.executeQuery(arr[a]);
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int cn = rsmd.getColumnCount();
                        

                        while (rs.next()) {
                            for(int i = 0; i<cn; i++){
                                    attr[i] = rs.getString(i+1).toString();
                            }
                            for(int i = 0; i<cn; i++){
                                    //System.out.print(attr[i] + "\t\t");
                                    temp = temp + attr[i] + "\t\t";
                            }
                            //System.out.println("");
                            temp = temp + "\n";
                        }
                        jTextArea1.setText(temp);
                        rs.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } 
        } 
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               
        String[] arr = {"INSERT INTO PRODUCT VALUES ('delivered', 'batman', 'DVD', 20, 'action', 12.99, 10, 200, 13)",
            "INSERT INTO PRODUCT VALUES ('waiting', 'the wall', 'CD', 16, 'rock', 15.99, 20, 556, 75)",
            "INSERT INTO PRODUCT VALUES ('delivered', 'the martian', 'DVD', 50, 'sci fi', 12.99, 15, 200, 45)",
            "INSERT INTO PRODUCT VALUES ('waiting', 'star wars', 'DVD', 41, 'sci fi', 12.99, 15, 131, 66)",
            "INSERT INTO PRODUCT VALUES ('waiting', 'bourne', 'DVD', 33, 'action', 11.99, 20, 340, 81)"
        };
        
        Database.ConnectToDB();
        String[] attr = new String[20];
        String temp = "";
     
        for(int a = 0; a < arr.length; a++ )
        {
            try{
                        Statement st = conn.createStatement();
                        ResultSet rs = st.executeQuery(arr[a]);
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int cn = rsmd.getColumnCount();
                        

                        while (rs.next()) {
                            for(int i = 0; i<cn; i++){
                                    attr[i] = rs.getString(i+1).toString();
                            }
                            for(int i = 0; i<cn; i++){
                                    //System.out.print(attr[i] + "\t\t");
                                    temp = temp + attr[i] + "\t\t";
                            }
                            //System.out.println("");
                            temp = temp + "\n";
                        }
                        jTextArea1.setText(temp);
                        rs.close();
                    } catch (Exception e) {
                        e.printStackTrace();
                    } 
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Populate_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Populate_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Populate_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Populate_Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Populate_Tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
